"""module router para cargar modulos pagados

Revision ID: 2e685db8364c
Revises: 16203049f29e
Create Date: 2026-07-20 13:13:20.213377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e685db8364c'
down_revision: Union[str, Sequence[str], None] = '16203049f29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_entries_company_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_employee_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_project_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_stage'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_task'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_total_minutes'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_work_date'), table_name='time_entries')
    op.drop_table('time_entries')
    op.add_column('moduls', sa.Column('module_route', sa.String(), nullable=True))
    op.create_index(op.f('ix_moduls_module_route'), 'moduls', ['module_route'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moduls_module_route'), table_name='moduls')
    op.drop_column('moduls', 'module_route')
    op.create_table('time_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage', postgresql.ENUM('planning', 'cutting', 'pre_assembly', 'lamination', 'truck_loading', 'installation', 'finishing', 'correction', 'other', name='projectstageenum'), autoincrement=False, nullable=False),
    sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('total_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('time_entries_company_id_fkey')),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name=op.f('time_entries_employee_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('time_entries_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('time_entries_pkey'))
    )
    op.create_index(op.f('ix_time_entries_work_date'), 'time_entries', ['work_date'], unique=False)
    op.create_index(op.f('ix_time_entries_total_minutes'), 'time_entries', ['total_minutes'], unique=False)
    op.create_index(op.f('ix_time_entries_task'), 'time_entries', ['task'], unique=False)
    op.create_index(op.f('ix_time_entries_stage'), 'time_entries', ['stage'], unique=False)
    op.create_index(op.f('ix_time_entries_project_id'), 'time_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_time_entries_id'), 'time_entries', ['id'], unique=False)
    op.create_index(op.f('ix_time_entries_employee_id'), 'time_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_time_entries_company_id'), 'time_entries', ['company_id'], unique=False)
    # ### end Alembic commands ###
