"""moduls

Revision ID: 3312dbb7c1a9
Revises: 
Create Date: 2026-06-29 09:37:41.962519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3312dbb7c1a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_legal_name'), 'companies', ['legal_name'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_tax_id'), 'companies', ['tax_id'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('basic', 'premium', 'enterprise', name='plansenum'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_amount'), 'plans', ['amount'], unique=False)
    op.create_index(op.f('ix_plans_currency'), 'plans', ['currency'], unique=False)
    op.create_index(op.f('ix_plans_external_id'), 'plans', ['external_id'], unique=False)
    op.create_index(op.f('ix_plans_frequency'), 'plans', ['frequency'], unique=False)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('temp_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Integer(), nullable=False),
    sa.Column('verification_code', sa.String(), nullable=True),
    sa.Column('verification_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('company_join_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_join_requests_company_id'), 'company_join_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_join_requests_id'), 'company_join_requests', ['id'], unique=False)
    op.create_index(op.f('ix_company_join_requests_message'), 'company_join_requests', ['message'], unique=False)
    op.create_index(op.f('ix_company_join_requests_status'), 'company_join_requests', ['status'], unique=False)
    op.create_index(op.f('ix_company_join_requests_user_id'), 'company_join_requests', ['user_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=True)
    op.create_table('debts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('creditor', sa.String(), nullable=False),
    sa.Column('number_of_installments', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'cancelled', 'paid', 'overdue', name='debtstatusenum'), nullable=False),
    sa.Column('notification', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_amount'), 'debts', ['amount'], unique=False)
    op.create_index(op.f('ix_debts_company_id'), 'debts', ['company_id'], unique=False)
    op.create_index(op.f('ix_debts_creditor'), 'debts', ['creditor'], unique=False)
    op.create_index(op.f('ix_debts_id'), 'debts', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_item_name'), 'inventory', ['item_name'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('production',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_client_name'), 'production', ['client_name'], unique=False)
    op.create_index(op.f('ix_production_id'), 'production', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('carpenter_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('delivery', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('planning', 'cutting', 'pre_assembly', 'lamination', 'truck_loading', 'installation', 'completed', 'cancelled', name='statusenum'), nullable=False),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['carpenter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_active'), 'projects', ['active'], unique=False)
    op.create_index(op.f('ix_projects_address'), 'projects', ['address'], unique=False)
    op.create_index(op.f('ix_projects_carpenter_id'), 'projects', ['carpenter_id'], unique=False)
    op.create_index(op.f('ix_projects_client_name'), 'projects', ['client_name'], unique=False)
    op.create_index(op.f('ix_projects_company_id'), 'projects', ['company_id'], unique=False)
    op.create_index(op.f('ix_projects_delivery'), 'projects', ['delivery'], unique=False)
    op.create_index(op.f('ix_projects_description'), 'projects', ['description'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_pdf_path'), 'projects', ['pdf_path'], unique=False)
    op.create_index(op.f('ix_projects_photo_path'), 'projects', ['photo_path'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('schedule_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_categories_company_id'), 'schedule_categories', ['company_id'], unique=False)
    op.create_index(op.f('ix_schedule_categories_id'), 'schedule_categories', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_categories_name'), 'schedule_categories', ['name'], unique=False)
    op.create_table('sells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('income', sa.DECIMAL(), nullable=False),
    sa.Column('expenses', sa.DECIMAL(), nullable=False),
    sa.Column('profit', sa.DECIMAL(), sa.Computed('income - expenses', ), nullable=True),
    sa.Column('status', sa.Enum('planning', 'cutting', 'pre_assembly', 'lamination', 'truck_loading', 'installation', 'completed', 'cancelled', name='statusenum'), nullable=False),
    sa.Column('date_sell', sa.Date(), nullable=False),
    sa.Column('delivery', sa.Date(), nullable=False),
    sa.Column('carpenter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carpenter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sells_client_id'), 'sells', ['client_id'], unique=False)
    op.create_index(op.f('ix_sells_client_name'), 'sells', ['client_name'], unique=False)
    op.create_index(op.f('ix_sells_company_id'), 'sells', ['company_id'], unique=False)
    op.create_index(op.f('ix_sells_expenses'), 'sells', ['expenses'], unique=False)
    op.create_index(op.f('ix_sells_id'), 'sells', ['id'], unique=False)
    op.create_index(op.f('ix_sells_income'), 'sells', ['income'], unique=False)
    op.create_index(op.f('ix_sells_installments'), 'sells', ['installments'], unique=False)
    op.create_index(op.f('ix_sells_profit'), 'sells', ['profit'], unique=False)
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('current_period_start', sa.Date(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Date(), nullable=True),
    sa.Column('current_period_end', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('payment_provider_id', sa.String(), nullable=True),
    sa.Column('provider_subscription_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', 'EXPIRED', 'REFUNDED', name='subscriptionstatusenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_amount'), 'subscription', ['amount'], unique=False)
    op.create_index(op.f('ix_subscription_cancel_at_period_end'), 'subscription', ['cancel_at_period_end'], unique=False)
    op.create_index(op.f('ix_subscription_company_id'), 'subscription', ['company_id'], unique=False)
    op.create_index(op.f('ix_subscription_current_period_end'), 'subscription', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_subscription_current_period_start'), 'subscription', ['current_period_start'], unique=False)
    op.create_index(op.f('ix_subscription_frequency'), 'subscription', ['frequency'], unique=False)
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plan_id'), 'subscription', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscription_user_id'), 'subscription', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('income', 'expense', name='transactiontypeenum'), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('sale', 'rent', 'other_income', 'salary', 'purchases', 'utilities', 'debt_payment', 'receivable_payment', 'material', name='transactioncategoryenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('is_variable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_amount'), 'transactions', ['amount'], unique=False)
    op.create_index(op.f('ix_transactions_company_id'), 'transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_description'), 'transactions', ['description'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_reference_id'), 'transactions', ['reference_id'], unique=False)
    op.create_table('weekly_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('shared_token', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shared_token')
    )
    op.create_index(op.f('ix_weekly_schedules_company_id'), 'weekly_schedules', ['company_id'], unique=False)
    op.create_index(op.f('ix_weekly_schedules_end'), 'weekly_schedules', ['end'], unique=False)
    op.create_index(op.f('ix_weekly_schedules_id'), 'weekly_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_schedules_start'), 'weekly_schedules', ['start'], unique=False)
    op.create_index(op.f('ix_weekly_schedules_title'), 'weekly_schedules', ['title'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_author_name'), 'comments', ['author_name'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_project_id'), 'comments', ['project_id'], unique=False)
    op.create_index(op.f('ix_comments_session_token'), 'comments', ['session_token'], unique=False)
    op.create_index(op.f('ix_comments_text'), 'comments', ['text'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'cancelled', 'paid', 'overdue', name='debtstatusenum'), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=True),
    sa.Column('total_installments', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_amount'), 'payments', ['amount'], unique=False)
    op.create_index(op.f('ix_payments_company_id'), 'payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payments_due_date'), 'payments', ['due_date'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('projects_pdfs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_pdfs_id'), 'projects_pdfs', ['id'], unique=False)
    op.create_index(op.f('ix_projects_pdfs_pdf_path'), 'projects_pdfs', ['pdf_path'], unique=False)
    op.create_index(op.f('ix_projects_pdfs_project_id'), 'projects_pdfs', ['project_id'], unique=False)
    op.create_table('projects_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_photos_id'), 'projects_photos', ['id'], unique=False)
    op.create_index(op.f('ix_projects_photos_photo_path'), 'projects_photos', ['photo_path'], unique=False)
    op.create_index(op.f('ix_projects_photos_project_id'), 'projects_photos', ['project_id'], unique=False)
    op.create_table('receivables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=True),
    sa.Column('payer_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'cancelled', 'overdue', name='receivablesstatusenum'), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('notification', sa.Boolean(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=True),
    sa.Column('numero_cuota_format', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receivables_amount'), 'receivables', ['amount'], unique=False)
    op.create_index(op.f('ix_receivables_company_id'), 'receivables', ['company_id'], unique=False)
    op.create_index(op.f('ix_receivables_description'), 'receivables', ['description'], unique=False)
    op.create_index(op.f('ix_receivables_due_date'), 'receivables', ['due_date'], unique=False)
    op.create_index(op.f('ix_receivables_id'), 'receivables', ['id'], unique=False)
    op.create_index(op.f('ix_receivables_numero_cuota'), 'receivables', ['numero_cuota'], unique=False)
    op.create_index(op.f('ix_receivables_numero_cuota_format'), 'receivables', ['numero_cuota_format'], unique=False)
    op.create_index(op.f('ix_receivables_payer_id'), 'receivables', ['payer_id'], unique=False)
    op.create_index(op.f('ix_receivables_payer_name'), 'receivables', ['payer_name'], unique=False)
    op.create_index(op.f('ix_receivables_receiver_id'), 'receivables', ['receiver_id'], unique=False)
    op.create_table('schedule_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weekly_schedule_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['schedule_categories.id'], ),
    sa.ForeignKeyConstraint(['weekly_schedule_id'], ['weekly_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_tasks_id'), 'schedule_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_tasks_weekly_schedule_id'), 'schedule_tasks', ['weekly_schedule_id'], unique=False)
    op.create_table('shared_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_projects_company_id'), 'shared_projects', ['company_id'], unique=False)
    op.create_index(op.f('ix_shared_projects_id'), 'shared_projects', ['id'], unique=False)
    op.create_index(op.f('ix_shared_projects_project_id'), 'shared_projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_shared_projects_token'), 'shared_projects', ['token'], unique=True)
    op.create_table('weekly_milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weekly_schedule_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['weekly_schedule_id'], ['weekly_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_milestones_id'), 'weekly_milestones', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_milestones_weekly_schedule_id'), 'weekly_milestones', ['weekly_schedule_id'], unique=False)
    op.create_foreign_key(
        'fk_companies_owner_id_users',
        'companies',
        'users',
        ['owner_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_milestones_weekly_schedule_id'), table_name='weekly_milestones')
    op.drop_index(op.f('ix_weekly_milestones_id'), table_name='weekly_milestones')
    op.drop_table('weekly_milestones')
    op.drop_index(op.f('ix_shared_projects_token'), table_name='shared_projects')
    op.drop_index(op.f('ix_shared_projects_project_id'), table_name='shared_projects')
    op.drop_index(op.f('ix_shared_projects_id'), table_name='shared_projects')
    op.drop_index(op.f('ix_shared_projects_company_id'), table_name='shared_projects')
    op.drop_table('shared_projects')
    op.drop_index(op.f('ix_schedule_tasks_weekly_schedule_id'), table_name='schedule_tasks')
    op.drop_index(op.f('ix_schedule_tasks_id'), table_name='schedule_tasks')
    op.drop_table('schedule_tasks')
    op.drop_index(op.f('ix_receivables_receiver_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_payer_name'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_payer_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_numero_cuota_format'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_numero_cuota'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_due_date'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_description'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_company_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_amount'), table_name='receivables')
    op.drop_table('receivables')
    op.drop_index(op.f('ix_projects_photos_project_id'), table_name='projects_photos')
    op.drop_index(op.f('ix_projects_photos_photo_path'), table_name='projects_photos')
    op.drop_index(op.f('ix_projects_photos_id'), table_name='projects_photos')
    op.drop_table('projects_photos')
    op.drop_index(op.f('ix_projects_pdfs_project_id'), table_name='projects_pdfs')
    op.drop_index(op.f('ix_projects_pdfs_pdf_path'), table_name='projects_pdfs')
    op.drop_index(op.f('ix_projects_pdfs_id'), table_name='projects_pdfs')
    op.drop_table('projects_pdfs')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_due_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_amount'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_comments_text'), table_name='comments')
    op.drop_index(op.f('ix_comments_session_token'), table_name='comments')
    op.drop_index(op.f('ix_comments_project_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_name'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_weekly_schedules_title'), table_name='weekly_schedules')
    op.drop_index(op.f('ix_weekly_schedules_start'), table_name='weekly_schedules')
    op.drop_index(op.f('ix_weekly_schedules_id'), table_name='weekly_schedules')
    op.drop_index(op.f('ix_weekly_schedules_end'), table_name='weekly_schedules')
    op.drop_index(op.f('ix_weekly_schedules_company_id'), table_name='weekly_schedules')
    op.drop_table('weekly_schedules')
    op.drop_index(op.f('ix_transactions_reference_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_description'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_company_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_amount'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_subscription_user_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_plan_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_frequency'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_current_period_start'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_current_period_end'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_company_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_cancel_at_period_end'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_amount'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_sells_profit'), table_name='sells')
    op.drop_index(op.f('ix_sells_installments'), table_name='sells')
    op.drop_index(op.f('ix_sells_income'), table_name='sells')
    op.drop_index(op.f('ix_sells_id'), table_name='sells')
    op.drop_index(op.f('ix_sells_expenses'), table_name='sells')
    op.drop_index(op.f('ix_sells_company_id'), table_name='sells')
    op.drop_index(op.f('ix_sells_client_name'), table_name='sells')
    op.drop_index(op.f('ix_sells_client_id'), table_name='sells')
    op.drop_table('sells')
    op.drop_index(op.f('ix_schedule_categories_name'), table_name='schedule_categories')
    op.drop_index(op.f('ix_schedule_categories_id'), table_name='schedule_categories')
    op.drop_index(op.f('ix_schedule_categories_company_id'), table_name='schedule_categories')
    op.drop_table('schedule_categories')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_photo_path'), table_name='projects')
    op.drop_index(op.f('ix_projects_pdf_path'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_description'), table_name='projects')
    op.drop_index(op.f('ix_projects_delivery'), table_name='projects')
    op.drop_index(op.f('ix_projects_company_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_carpenter_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_address'), table_name='projects')
    op.drop_index(op.f('ix_projects_active'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_production_id'), table_name='production')
    op.drop_index(op.f('ix_production_client_name'), table_name='production')
    op.drop_table('production')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_inventory_item_name'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_debts_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_creditor'), table_name='debts')
    op.drop_index(op.f('ix_debts_company_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_amount'), table_name='debts')
    op.drop_table('debts')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_company_join_requests_user_id'), table_name='company_join_requests')
    op.drop_index(op.f('ix_company_join_requests_status'), table_name='company_join_requests')
    op.drop_index(op.f('ix_company_join_requests_message'), table_name='company_join_requests')
    op.drop_index(op.f('ix_company_join_requests_id'), table_name='company_join_requests')
    op.drop_index(op.f('ix_company_join_requests_company_id'), table_name='company_join_requests')
    op.drop_table('company_join_requests')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_frequency'), table_name='plans')
    op.drop_index(op.f('ix_plans_external_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_currency'), table_name='plans')
    op.drop_index(op.f('ix_plans_amount'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_companies_tax_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_legal_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
