"""moduls 4

Revision ID: 519e381c3e33
Revises: a8bdfd73fe1a
Create Date: 2026-07-06 09:06:08.059431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519e381c3e33'
down_revision: Union[str, Sequence[str], None] = 'a8bdfd73fe1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moduls', sa.Column('icon_url', sa.String(), nullable=True))
    op.alter_column('moduls', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_moduls_icon_url'), 'moduls', ['icon_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moduls_icon_url'), table_name='moduls')
    op.alter_column('moduls', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('moduls', 'icon_url')
    # ### end Alembic commands ###
