"""moduls 2

Revision ID: 661387e5497e
Revises: 3312dbb7c1a9
Create Date: 2026-06-29 09:43:29.498768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '661387e5497e'
down_revision: Union[str, Sequence[str], None] = '3312dbb7c1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moduls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moduls_id'), 'moduls', ['id'], unique=False)
    op.create_index(op.f('ix_moduls_name'), 'moduls', ['name'], unique=False)
    op.create_index(op.f('ix_moduls_price'), 'moduls', ['price'], unique=False)
    op.create_index(op.f('ix_moduls_slug'), 'moduls', ['slug'], unique=False)
    op.create_table('moduls_companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modul_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['modul_id'], ['moduls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'modul_id', name='uq_company_module')
    )
    op.create_index(op.f('ix_moduls_companies_id'), 'moduls_companies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moduls_companies_id'), table_name='moduls_companies')
    op.drop_table('moduls_companies')
    op.drop_index(op.f('ix_moduls_slug'), table_name='moduls')
    op.drop_index(op.f('ix_moduls_price'), table_name='moduls')
    op.drop_index(op.f('ix_moduls_name'), table_name='moduls')
    op.drop_index(op.f('ix_moduls_id'), table_name='moduls')
    op.drop_table('moduls')
    # ### end Alembic commands ###
