"""module icon

Revision ID: 840effa772d3
Revises: 2e685db8364c
Create Date: 2026-07-20 13:18:14.802307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840effa772d3'
down_revision: Union[str, Sequence[str], None] = '2e685db8364c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moduls', sa.Column('icon', sa.String(), nullable=True))
    op.create_index(op.f('ix_moduls_icon'), 'moduls', ['icon'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moduls_icon'), table_name='moduls')
    op.drop_column('moduls', 'icon')
    # ### end Alembic commands ###
