"""moduls 3

Revision ID: a8bdfd73fe1a
Revises: 6b709406d879
Create Date: 2026-07-05 14:55:03.774738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8bdfd73fe1a'
down_revision: Union[str, Sequence[str], None] = '6b709406d879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moduls', sa.Column('description', sa.String(), nullable=False))
    op.create_index(op.f('ix_moduls_description'), 'moduls', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moduls_description'), table_name='moduls')
    op.drop_column('moduls', 'description')
    # ### end Alembic commands ###
